pages:
  stage: deploy
  # The Docker image that will be used to build your app
  image: alpine
  # Functions that should be executed before the build script is run
  before_script:
    - apk add --no-cache make doxygen graphviz
  script:
    - make doc
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - doc/public
  publish: doc/public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  tags:
    - kubernetes

