repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-xml
      - id: check-json
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=2"
          - "--no-sort-keys"
          - "--no-ensure-ascii"
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-case-conflict
  - repo: local
    hooks:
      - id: make
        name: make (compile-test)
        stages: [pre-push]
        language: system
        entry: sh -c 'OUT_PATH=pre-commit-test/build/ ; make OPATH=${OUT_PATH} DPATH=${OUT_PATH} EXEC=${OUT_PATH}sokoban ; rm -rf ${OUT_PATH}'
        pass_filenames: false
        always_run: true
      - id: make-ci
        name: make (ci-compile-test)
        stages: [manual]
        language: system
        entry: sh -c 'OUT_PATH=pre-commit-test/build/ ; make OPATH=${OUT_PATH} DPATH=${OUT_PATH} EXEC=${OUT_PATH}sokoban'
        pass_filenames: false
        always_run: true
      - id: make-doc
        name: make (doc-test)
        stages: [pre-push]
        language: system
        entry: sh -c 'OUT_PATH=pre-commit-test/doc/ ; make DOCPATH=${OUT_PATH} doc ; rm -rf ${OUT_PATH}'
        pass_filenames: false
        always_run: true
      - id: make-doc-ci
        name: make (ci-doc-test)
        stages: [manual]
        language: system
        entry: sh -c 'OUT_PATH=pre-commit-test/doc/ ; make DOCPATH=${OUT_PATH} doc'
        pass_filenames: false
        always_run: true
