name: test
on: [push, pull_request, workflow_dispatch]
env:
  PIP_CACHE_DIR: "${{ github.workspace }}/.cache/pip"
  PRE_COMMIT_HOME: "${{ github.workspace }}/.cache/pre-commit"
concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v3
      with:
        path: |
          .cache/
          .venv/
        key: ${{ runner.os }}-python
        restore-keys: |
          ${{ runner.os }}-python
    - name: Setup Python
      run: |
        python --version ; pip --version  # For debugging
        python -m venv .venv/
        source .venv/bin/activate
    - name: Install Dependencies
      run: |
        sudo apt -y update
        sudo apt -y install libncurses-dev libsdl2-dev graphviz doxygen
        pip install pre-commit
    - name: Check format
      run: pre-commit run -av
      continue-on-error: true
    - name: Check compilation
      run: pre-commit run -av --hook-stage manual make-ci
    - name: Check doc gen
      run: pre-commit run -av --hook-stage manual make-doc-ci
    - uses: actions/upload-artifact@v3
      with:
        name: "test-artifact"
        path: |
          pre-commit-test/
